use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // ── Resource embedding ──────────────────────────────────────────────
    embed_resource::compile("../icons/mhd.rc", embed_resource::NONE)
        .manifest_optional()
        .expect("failed to embed icon resource");

    // Copy mhd.ico next to the binary so the tray can load it directly
    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let profile_dir = out_dir.ancestors().nth(3).unwrap(); // …/target/debug/
    let ico_src = std::path::Path::new("../icons/mhd.ico");
    let ico_dst = profile_dir.join("mhd.ico");
    let _ = std::fs::copy(ico_src, &ico_dst);

    println!("cargo:rerun-if-changed=../icons/mHD_256.png");
    println!("cargo:rerun-if-changed=../icons/mhd.ico");
    println!("cargo:rerun-if-changed=../icons/mhd.rc");

    // ── Auto-bundle themes ──────────────────────────────────────────────
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let themes_dir = Path::new(&manifest_dir).join("..").join("themes");

    let mut entries: Vec<_> = fs::read_dir(&themes_dir)
        .expect("themes/ directory not found")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().and_then(|s| s.to_str()) == Some("json"))
        .collect();
    entries.sort_by_key(|e| e.path());

    let mut code = String::from(
        "/// Auto-generated by build.rs — do not edit manually.\n\
         const BUNDLED_THEMES: &[BundledTheme] = &[\n",
    );

    for entry in &entries {
        let filename = entry.file_name().to_string_lossy().to_string();
        // Generate a path relative to CARGO_MANIFEST_DIR, so include_str! resolves
        // from the mhd-daemon package root (not from OUT_DIR).
        let manifest_dir = manifest_dir.replace('\\', "/");
        code.push_str(&format!(
            "    BundledTheme {{\n        filename: \"{filename}\",\n        content: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../themes/{filename}\")),\n    }},\n"
        ));
    }

    code.push_str("];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("bundled_themes.rs"), &code)
        .expect("failed to write bundled_themes.rs");

    println!("cargo::rerun-if-changed={}", themes_dir.display());
}
